name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Authenticate to Google Cloud using WIF
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.0
      with:
        token: ${{ secrets.GCP_SA_KEY }}

    # Set up gcloud CLI environment
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Get the latest tag from the first GAR
    - name: Get latest tag
      id: latest-tag
      run: |
        TAGS=$(gcloud container images list-tags asia-northeast3-docker.pkg.dev/amazing-source-396109/repository/web --format="get(tags)" | tail -n +2 | tr ',' '\n' | sort -nr | head -1)
        echo "LATEST_TAG=${TAGS}" >> $GITHUB_ENV

    # Update Helm chart's values.yaml
    - name: Update values.yaml
      run: |
        sed -i 's/^  tag:.*/  tag: '${{ env.LATEST_TAG }}'/' helm-chart/values.yaml

    # Build a new Docker image with Helm chart and push to another GAR.
    - name: Build new Docker image with Helm chart
      run: docker build -t asia-northeast3-docker.pkg.dev/amazing-source-396109/cicd/my-new-image:$GITHUB_SHA .

    - name: Push new Docker image to the second GAR
      run: |
        docker push asia-northeast3-docker.pkg.dev/amazing-source-396109/cicd/my-new-image:$GITHUB_SHA

    # Deploy to GKE using Helm
    - name: Deploy to GKE
      run: |
        helm upgrade --install my-release-name ./helm-chart --set image.repository=asia-northeast3-docker.pkg.dev/amazing-source-396109/cicd/my-new-image,image.tag=$GITHUB_SHA


