name: release into the target GKE cluster

# Controls when the workflow will run

on:
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

                    
      - name: Helm tool installer
        uses: Azure/setup-helm@v3 

      - name: Print the Helm client version information
        run: helm version

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GKE_PROVIDER_ID }}
          service_account: ${{ secrets.GKE_SERVICE_ACCOUNT }}
          audience: 'https://github.com/Taewoogit/releng'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Install Google Cloud Auth plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get Kubernetes config
        run: gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.region }} --project ${{ secrets.PROJECT_ID }}

      - name: Examine the chart for possible issues
        run: helm lint ${{ inputs.chart_path }}

      - name: "[MANIFESTS] Dry-run the release"
        run: |
            helm upgrade ${{ inputs.release_name }} ${{ inputs.chart_path }} \
            --namespace ${{ inputs.namespace }} \
            --install \
            --dry-run

  deploy:
    needs: prepare
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
#      - name: Image tag is override - ${{ inputs.image_tag }}
#        if: ${{ inputs.image_tag != null && inputs.image_tag != ''}}
#        run: echo "OPT_IMAGE_TAG=--set-string image.tag=${{ inputs.image_tag }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
                    
      - name: Helm tool installer
        uses: Azure/setup-helm@v3 

      - name: Print the Helm client version information
        run: helm version

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GKE_PROVIDER_ID }}
          service_account: ${{ secrets.GKE_SERVICE_ACCOUNT }}
          audience: 'https://github.com/Taewoogit/releng'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1

      - name: Install Google Cloud Auth plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get Kubernetes config
        run: gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ inputs.region }} --project ${{ secrets.PROJECT_ID }}

      - name: Examine the chart for possible issues
        run: helm lint ${{ inputs.chart_path }}

      - name: Create Namespace
        run: kubectl create namespace nginx --dry-run=client -o yaml | kubectl apply -f -

      - name: Upgrade the release
        run: |
          helm upgrade ${{ inputs.release_name }} ${{ inputs.chart_path }} \
            --namespace ${{ inputs.namespace }} \
            --install 
