name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Authenticate to Google Cloud using WIF
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: projects/YOUR_PROJECT_NUMBER/locations/global/workloadIdentityPools/YOUR_POOL/providers/YOUR_PROVIDER
        service_account: 'YOUR_SERVICE_ACCOUNT@YOUR_PROJECT_ID.iam.gserviceaccount.com'
        audience: 'https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPOSITORY_NAME'

    # Set up gcloud CLI environment
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # Get the latest tag from the first GAR
    - name: Get latest tag
      id: latest-tag
      run: |
        TAGS=$(gcloud container images list-tags asia-northeast3-docker.pkg.dev/amazing-source-396109/repository/web --format="get(tags)" | tail -n +2 | tr ',' '\n' | sort -nr | head -1)
        echo "LATEST_TAG=${TAGS}" >> $GITHUB_ENV

    # Update Helm chart's values.yaml
    - name: Update values.yaml
      run: |
        sed -i 's/^  tag:.*/  tag: '${{ env.LATEST_TAG }}'/' helm-chart/values.yaml

    # Build a new Docker image with Helm chart and push to another GAR.
    - name: Build new Docker image with Helm chart
      run: docker build -t asia-northeast3-docker.pkg.dev/amazing-source-396109/cicd/my-new-image:$GITHUB_SHA .

    - name: Push new Docker image to the second GAR
      run: |
        docker push asia-northeast3-docker.pkg.dev/amazing-source-396109/cicd/my-new-image:$GITHUB_SHA

    # Deploy to GKE using Helm
    - name: Deploy to GKE
      run: |
        helm upgrade --install my-release-name ./helm-chart --set image.repository=asia-northeast3-docker.pkg.dev/amazing-source-396109/cicd/my-new-image,image.tag=$GITHUB_SHA
