name: "[Deploy] Nginx Upgrade the release"

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/deploy.yml
    with:
      chart_path: chart/helm/
      namespace: nginx
      region: asia-northeast3
      release_name: nginx
      image_tag: ${{ inputs.image_tag }}
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      GKE_PROVIDER_ID: ${{ secrets.GKE_PROVIDER_ID }}
      GKE_SERVICE_ACCOUNT: ${{ secrets.GKE_SERVICE_ACCOUNT }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
